In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.6.0+cu124


## Intro to Tensors

## Creating Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [8]:
scalar.ndim

0

In [15]:
# get tensor back as python int
scalar.item()

7

In [10]:
# vector
vector  = torch.tensor([1,2,3,4,5])
vector

tensor([1, 2, 3, 4, 5])

In [17]:
vector.ndim

1

In [18]:
vector.shape

torch.Size([2])

In [19]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [20]:
MATRIX.ndim

2

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [22]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [23]:
TENSOR.ndim

3

In [24]:
TENSOR.shape

torch.Size([1, 3, 3])

  ### Random Tensors

  `Start with random numbers -> look at the data -> update random numbers ->look at the data -> update random numbers`

In [25]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8318, 0.2593, 0.8684, 0.2087],
        [0.8742, 0.7097, 0.9505, 0.5977],
        [0.2905, 0.2987, 0.2624, 0.0896]])

In [26]:
random_tensor.ndim

2

In [27]:
random_tensor.shape

torch.Size([3, 4])

In [28]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones

In [29]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
# Tensors of ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [33]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatype

In [36]:
# float 32 tensor
float_32_tenosr = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what datatype it is
                               device=None,  # what device your data on
                               requires_grad=False  # you want the grad or not
                              )
float_32_tenosr


tensor([3., 6., 9.])